### ISSUE TITLE
Get dev instance of data warehouse up and running

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1918]
This is time sensitive as Shane needs to be able to scan this app for security checks.

Current status:
We have moved to working with the staging instance of the application. The warehouse loads, but API portion doesn't seem to be running. The status of the keycloak log in (which Shane will need to do a full scan) is also unknown at the moment.

**Comment by Mak-NOAA** [comment]
@BHHorness-NOAA @SaOgaz-NOAA here's the latest on this one

DEV URL is currently = https://www.devwebapps.nwfsc.noaa.gov/data/index.html and it points to NWCWD2

The front end loads however when calling the APIs (for example https://www.devwebapps.nwfsc.noaa.gov/data/api/v1/source/warehouse.taxonomy_dim/selection.csv?variables=common_name,scientific_name), we're now getting the following error:

```
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144] mod_wsgi (pid=7662): Target WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py' cannot be loaded as Python module.
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144] mod_wsgi (pid=7662): Exception occurred processing WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py'.
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144] Traceback (most recent call last):
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py", line 11, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     import wsgiApps
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/wsgiApps.py", line 12, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     from api.app import app as wsgiApp
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/__init__.py", line 6, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     from api import app as app_module #alias app Module, for intra-package use
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/app.py", line 31, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     from api.resources.source import (
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/source.py", line 12, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     from api.resources.source.selection import (
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/selection/defaults.py", line 8, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     from ..warehouse import util, warehouse
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/warehouse/util.py", line 6, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     from api.resources.source.data import util
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/data/util.py", line 49, in <module>
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     'db_config.ini': get_engine_from_config('db_config.ini')
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/data/util.py", line 29, in get_engine_from_config
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     ,'warehouse')
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/config_loader.py", line 145, in get_heading_dict
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144]     raise HeadingNotFoundError( str_heading)
[Sat Sep 26 23:05:44 2020] [error] [client 161.55.212.144] api.config_loader.HeadingNotFoundError: 'warehouse'
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144] mod_wsgi (pid=7664): Target WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py' cannot be loaded as Python module.
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144] mod_wsgi (pid=7664): Exception occurred processing WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py'.
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144] Traceback (most recent call last):
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py", line 11, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     import wsgiApps
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/wsgiApps.py", line 12, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     from api.app import app as wsgiApp
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/__init__.py", line 6, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     from api import app as app_module #alias app Module, for intra-package use
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/app.py", line 31, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     from api.resources.source import (
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/source.py", line 12, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     from api.resources.source.selection import (
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/selection/defaults.py", line 8, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     from ..warehouse import util, warehouse
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/warehouse/util.py", line 6, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     from api.resources.source.data import util
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/data/util.py", line 49, in <module>
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     'db_config.ini': get_engine_from_config('db_config.ini')
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/data/util.py", line 29, in get_engine_from_config
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     ,'warehouse')
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/config_loader.py", line 145, in get_heading_dict
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144]     raise HeadingNotFoundError( str_heading)
[Sat Sep 26 23:08:42 2020] [error] [client 161.55.212.144] api.config_loader.HeadingNotFoundError: 'warehouse'
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144] mod_wsgi (pid=7662): Target WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py' cannot be loaded as Python module.
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144] mod_wsgi (pid=7662): Exception occurred processing WSGI script '/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py'.
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144] Traceback (most recent call last):
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/mod_wsgi_application.py", line 11, in <module>
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]     import wsgiApps
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/wsgiApps.py", line 12, in <module>
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]     from api.app import app as wsgiApp
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/__init__.py", line 6, in <module>
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]     from api import app as app_module #alias app Module, for intra-package use
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/app.py", line 31, in <module>
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]     from api.resources.source import (
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]   File "/var/www/wsgi-scripts/warehouse/server/api/resources/source/source.py", line 8, in <module>
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144]     import api.json as json
[Sat Sep 26 23:11:43 2020] [error] [client 161.55.212.144] AttributeError: module 'api' has no attribute 'json'
```

@SaOgaz-NOAA I tried to mess around and update the source.py however I'm getting:
`Error:        	/var/www/wsgi-scripts/warehouse/server/api/resources/source/source.py: open for write: permission denied`

Let's connect this week and see what we can do about it or is there a way I can get

**Comment by Mak-NOAA** [comment]
Note, all codes can be found in the server folder here https://github.com/nwfsc-fram/warehouse

**Comment by Mak-NOAA** [comment]
https://stackoverflow.com/questions/64096075/attributeerror-module-api-has-no-attribute-json

**Comment by Mak-NOAA** [comment]
https://stackoverflow.com/questions/64131739/api-config-loader-headingnotfounderror-warehouse?noredirect=1#comment113407364_64131739

**Comment by SaOgaz-NOAA** [comment]
Finally got this working, will tip Shane off soon.
