### ISSUE TITLE
lerna bootstrap failing due to fibers module requiring node-gyp

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#467]
I'm stuck in a loop it seems where lerna bootstrap never successfully runs as it tries to compile the fibers module, which in turn requires node-gyp.  Are we using fiber or what other module might be using it?  I'm deleted the entire node_modules root directory, the package-lock.json file and I don't have a yarn.lock file, so unclear what is going on.

```
warning "workspace-aggregator-270668c0-d6c7-4b89-99a5-5a5c1b5694a7 > example > @vue/cli-plugin-e2e-cypress > eslint-plugin-cypress@2.2.1" has unmet peer dependency "eslint@>= 3.2.1".
[4/4] Building fresh packages...
[6/7] ⠈ fibers
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
error C:\Todd.Hay\Code\boatnet\node_modules\fibers: Command failed.
Exit code: 1
Command: node build.js || nodejs build.js
Arguments:
Directory: C:\Todd.Hay\Code\boatnet\node_modules\fibers
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.14.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Todd.Hay\Programs\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Todd.Hay\\Code\\boatnet\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Todd.Hay\Code\boatnet\node_modules\fibers
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`




lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'boatnet'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'boatnet'
```

**Comment by toddhay-NOAA** [comment]
So in my investigation, it seems that we have the following dependency on node-gyp:

@lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp

(navigate the @lerna/bootstrap path of dependencies to see this: https://www.npmjs.com/package/@lerna/bootstrap)

so how are we getting away from using node-gyp when we use lerna bootstrap so heavily?  What am I missing here?

**Comment by toddhay-NOAA** [comment]
For what it's worth there are 6 @lerna modules that all require the @lerna/run-lifecycle module, and thus node-gyp.

**Comment by toddhay-NOAA** [comment]
Installing node-gyp via:

`yarn add node-gyp`

that did the trick and now lerna bootstrap executes without failing.

**Comment by toddhay-NOAA** [comment]
and now I even have a yarn.lock file.

**Comment by wsmith-nwfsc** [comment]
What yarn version do you have?

**Comment by toddhay-NOAA** [comment]
1.16.0
